### ISSUE TITLE
File write problem.

### ISSUE THREAD

**Issue by ldvy** [songquanpeng/filesystem-emulator#1]
Hi mate,

I just happened to come across your project and noticed that the editFile function does not work.
When we create and edit a new file, and then "cat" the content, it returns nothing.

I was just wondering if you had a chance to investigate this, and perhaps already know what might be going wrong.

Thanks!

**Comment by songquanpeng** [comment]
![image](https://user-images.githubusercontent.com/39998050/142747561-e3842d65-9282-4553-b8a6-72c35268f2d6.png)
It works.

I think the problem is it output too much blank lines when you use the  cat command. You should scroll the terminal to check the initial lines.
